### PR TITLE
Ignore test by browser

### PR DESCRIPTION
**Pull request by AdrianCozma**

### CODE REVIEW

**Comment by AdrianCozma** [comment]
@dpwspoon please review, going this way for ignoring tasks would mean we will have separate grunt tasks for test suites that can't be run on all browsers

While testing this I noticed that the mechanism to update the build status in Sauce Labs is a bit flawed because the update takes place in the `afterAll` hook of each suite, so if the first suite would fail and then a second suite would pass the end result in Sauce Labs would be `passed`. Because of this I think we need to do this update after all suites have been executed.

**Comment by dpwspoon** [comment]
Hmm, that's too bad.  If we kept going down this track then we could maybe on travis use a different mocha reporter that sends to a file, ([one example](https://www.npmjs.com/package/mocha-spec-json-reporter)).  And then upload the tests afterwards, but that seems like a solution designed to fit our current problem and not on the correct track.  Maybe it would be better to look at doing the skips.

**Comment by dpwspoon** [comment]
At the very least, it still shows that it is failing in travis though right?

**Comment by AdrianCozma** [comment]
yes the results in Travis are accurate

**Pull request merged**
